### ISSUE TITLE
Using ol-ext node modules in webpack

### ISSUE THREAD

**Issue by SamuelIrungu** [darkscript/ol-ol-ext-webpack-example#1]
I haven't found a good solution yet to import ol-ext node module files to my webpack configured project, not sure if in ol-ext node module packages it was necessary to do "import ol from ol" in all files and also include package.json and add openlayers and jquery as dependencies required for ol-ext to work. Maybe the ol-ext node module is not well functioning, the openlayers(ol) node module is easy to use though.

I tried the following simple test;

```javascript
 import 'ol/ol.css';
 import 'ol-ext/control/permalinkcontrol.css'
 import 'ol-ext/control/searchphotoncontrol'
 //import 'ol'
 import ol from 'ol'
 import Map from 'ol/map';
 import View from 'ol/view';
 import TileLayer from 'ol/layer/tile';
 import XYZ from 'ol/source/xyz';
 import ol_Scaleline from 'ol/control/scaleline'
 import Control from 'ol/control'
 import Permalink from 'ol-ext/control/permalinkcontrol';
 import SearchPhoton from 'ol-ext/control/searchphotoncontrol'

 new Map({
  target: 'map',
  layers: [
    new TileLayer({
      source: new XYZ({
        url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png'
      })
    })
  ],
  controls: Control.defaults().extend([
      new ol_Scaleline(),
      //TODO: Here is where we have the issue, how do we import the ol-ext files to the project
      new Permalink(),
      new SearchPhoton()
  ]),
  view: new View({
    center: [0, 0],
    zoom: 2
  })
}); 
```

It doesn't work though.

**Comment by Viglino** [comment]
Hello,
ol-ext doesn't use [ES2016 module syntax](http://exploringjs.com/es6/ch_modules.html) and doesn't import ol dependencies...
Look at the [ol-ext permalinkcontrol.js](https://github.com/Viglino/ol-ext/blob/gh-pages/control/permalinkcontrol.js) and the [ol control/FullScreen.js](https://github.com/openlayers/openlayers/blob/master/src/ol/control/FullScreen.js) to see difference in declaration...
...

**Comment by SamuelIrungu** [comment]
I think then for the ol-ext node modules to be usable and for us to be able to import the separate files, we will have to improve the files to [look something like this](https://github.com/darkscript/ol-ol-ext-webpack-example/blob/master/suggested_ol_ext_node_modules_structure/permalinkcontrol.js), for all the ol-ext classes in node modules, am I right?

**Comment by Viglino** [comment]
Yes, something like that...

**Comment by SamuelIrungu** [comment]
Maybe I can try to improve the node module over the weekend, I will share what I will have next week, thanks much

**Comment by Viglino** [comment]
Great!
You can try just with a simple class with no dependencies (permalink just hangs on ol.control.Control) before others (that import jQuery and ol classes).

**Comment by SamuelIrungu** [comment]
Okay

**Comment by Siedlerchr** [comment]
A while ago I faced the same problem and I could solve it my modifying the structure a bit.
For example the layercontrol/layerswitcher 
I simply had to delete the namespace stuff mostly and add export statements in front of the "public" methods.

https://github.com/darkscript/ol-ol-ext-webpack-example/commit/6ac3ed3a23f593762aa8b01c234155203fe8c873#diff-d6b5e9fb2643a30d929cb8c242ecb8b7

Edit// And then I could use it like this in my project
```js

import 'ol/ol.css';
import Map from 'ol/map';
import View from 'ol/view';
import TileLayer from 'ol/layer/tile';
import OSM from 'ol/source/osm';
import Proj from 'ol/proj';
import Overlay from 'ol/overlay';
import Feature from 'ol/feature'
import Point from "ol/geom/point";
import Style from 'ol/style/style';
import Icon from 'ol/style/icon';
import Vector from 'ol/source/vector';
import VectorLayer from 'ol/layer/vector';
import Control from 'ol/control'
import LayerPopup from "./ol3ext/layerpopupcontrol";


function getMapVar() {
    let map = new Map({
        target: 'map',
        layers: [
            new TileLayer({
                source: new OSM(),
                baseLayer: true, //Base Layer are exklusively shown, only one at a time
                displayInLayerSwitcher: true,
                title: 'OSM Layer'
            })
        ],
        view: new View({
            // 51.738045, 8.949225
            center: Proj.transform([8.949225, 51.738045], 'EPSG:4326', 'EPSG:3857'),
            zoom: 12
        }),
        controls: Control.defaults().extend
        ([
            new LayerPopup(),
        ]),
    });
    let popup = new Overlay({
        element: element //the html element ,
        positioning: 'bottom-center',
        stopEvent: false,
        offset: [0, -50],
        id: "popup",
    });
    map.addOverlay(popup);
return map;
}
```

**Comment by SamuelIrungu** [comment]
Yeah am doing exactly that now and am really using many classes from ol-ext so I want to re-create ol-ext node module with import and export and I will share then if its approved, we can improve the main node module.

**Comment by Viglino** [comment]
@darkscript tell us when you get something.
I'll try to test it when I get some time!

**Comment by SamuelIrungu** [comment]
ok I hope to have something by Monday morning

**Comment by SamuelIrungu** [comment]
@Viglino Some good news, I just finished recreating ol-ext node modules with required import, export structure, check it out and test it [here](https://github.com/darkscript/ol-ext)

**Comment by SamuelIrungu** [comment]
I also updated this example project to help anyone who may need to start up with ol-ext, ol and webpack.
