### ISSUE TITLE
mobile TouchNavigation

### ISSUE THREAD

**Issue by ayacoub1** [darkscript/ol-ol-ext-webpack-example#4]
hi , i need to implement touch navigation (two finger for mobile browser ) ?

**Comment by SamuelIrungu** [comment]
Hi @ayacoub1, sorry I didn't get back earlier, openlayers already manage that, you can use two finger to zoom for instance. Or did you mean something different

**Comment by ayacoub1** [comment]
No i mean when you use openlayers map on mobile browser , i need the only way to zoom or navigate by using two finger like following example
http://dev.openlayers.org/examples/mobile-navigation.html

**Comment by SamuelIrungu** [comment]
try https://github.com/darkscript/ol-ol-ext-webpack-example/commit/f5be586f7dac020b2fe48640913a2e4252d825e2

**Comment by ayacoub1** [comment]
Thank you for reply and help, its partially working , like I cant zoom on double click ,but still I can pan using touch (one finger), please look to google map behavior here https://developers.google.com/maps/documentation/javascript/interaction
